<?php
sleep(2);
require '../../vendor/autoload.php';

use Google\Auth\Credentials\ServiceAccountCredentials;
use Google\Auth\HttpHandler\HttpHandlerFactory;

$credential = new ServiceAccountCredentials(
    "https://www.googleapis.com/auth/firebase.messaging",
    json_decode(file_get_contents("../../pvKey.json"), true)
);

$token = $credential->fetchAuthToken(HttpHandlerFactory::build());

include("../../../database/connection.php");

$requestPayLoad = file_get_contents("php://input");

$login_object = json_decode($requestPayLoad, true);

for($i = 0; $i < count($login_object['notification_hint']); $i++){

//starts
// public class Chat_message_notification_details_data {
//     private String sender_id, receiver_id, product_id;
//     private String username, notification_action, user_status;

//     public Chat_message_notification_details_data(String sender_id, String receiver_id, String product_id, String username, String notification_action, String user_status) {
//         this.username = username;
//         this.sender_id = sender_id;
//         this.receiver_id = receiver_id;
//         this.product_id = product_id;
//         this.notification_action = notification_action;
//         this.user_status = user_status;
//     }
// }
//ends

    $post_id = $login_object['notification_hint'][$i]['post_id'];
	 $image = $login_object['notification_hint'][$i]['post_img'];
     	 $icon = $login_object['notification_hint'][$i]['post_img'];
         $accesstoken = $token['access_token'];
      $body_message = $login_object['notification_hint'][$i]['body_message'];
    $details_message = $login_object['notification_hint'][$i]['details_message'];
    $title_message = $login_object['notification_hint'][$i]['title_message'];
$folder_main = "direct_chat";
$folder_sub = "folder_sub_here";
$folder_icon_main = "folder_icon_main_here";
$folder_icon_sub = "folder_icon_sub_here";
$url_code = "url_code_here";
$action = "action_here";
       $to = $login_object['notification_hint'][$i]['topic'];
      //topics = fundi, mteja, duka, all_user


$data = array(
    'icon' => $icon,
	'folder_icon_main' => $folder_icon_main,
	'folder_icon_sub' => $folder_icon_sub,
	'action_id' => $post_id,
	'url_code' => $url_code,
	'title_message' => $title_message,
	'body_message' => $body_message,
	'details_message' => $details_message,
    'folder_main' => $folder_main,
	'folder_sub' => $folder_sub,
    'image' => $image,
    'action' => $action
);
$topic_not = array(
    'topic' => $to,
    'data'=> $data
);
$feilds = array(
    'message' => $topic_not
);

$feilds_array = json_encode($feilds);

//{\n  \"message\": {\n    \"topic\" : \"foo-bar\",\n    \"notification\": {\n
// \"body\": \"This is a Firebase Cloud Messaging Topic Message!\",\n      \"title\": \"FCM Message\"\n    }\n  }\n}

sendNotif($post_id, $feilds_array, $accesstoken);
}
function sendNotif ($post_id, $feilds_array, $accesstoken){
  $response_fundis = [];
       
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/v1/projects/fundishop-f5b04/messages:send');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $feilds_array);

$headers = array();
$headers[] = 'Authorization: Bearer '.$accesstoken;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
       $response_fundi_data = [
            "post_id"=>$post_id,
            "status"=>"notification_failed",
            "message"=>"notification failed",
            "error"=>curl_error($ch)
          ];
       
         $response_fundis[] = $response_fundi_data;
}else{
       $response_fundi_data = [
            "post_id"=>$post_id,
            "status"=>"notification_successfully",
            "message"=>"notification successfully",
            "result"=>$result
          ];
       
         $response_fundis[] = $response_fundi_data;
}

echo json_encode($response_fundis);

curl_close($ch);
}

?>